Refactor project structure

diff --git a/.github/workflows/revive-lint.yml b/.github/workflows/revive-lint.yml
--- a/.github/workflows/revive-lint.yml
+++ b/.github/workflows/revive-lint.yml
@@ -1,4 +1,4 @@
-name: Lint & Test
+name: Code Checker
 on:
   pull_request:
     branches:
@@ -9,32 +9,57 @@ on:
       - master
       - develop
     paths:
-      - '*/.go'
       - 'revive.toml'
       - '.github/workflows/revive-lint.yml'
 
 jobs:
 
   lint:
-    name: Lint & Test Service
+    name: 👩🏼‍🌾 Lint and Test
     runs-on: ubuntu-latest
     steps:
-
-    - name: Set up Go
-      uses: actions/setup-go@v2
+    - uses: actions/checkout@v2
+    - name: 🔧 Print current working dir
+      run: |
+        ls -la $PWD
+        ls -la $GITHUB_WORKSPACE
+    - uses: actions/setup-go@v2
       with:
-        go-version: '1.17'
+        go-version: '1.21.1'
 
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
-    
-    - name: Run Test
-      run: 	go test -v -cover ./...
+    - name: ⚙️ Setup GO environment
+      run: |
+            go mod download
 
-    - name: Run Revive Action
+    - name: 👷 Build
+      run: go build ./cmd/app.go 
+
+    - name: 🧪 Run Unit tests
+      run: |
+            sudo go test ./... -coverprofile coverage.out -covermode count
+            sudo go tool cover -func coverage.out
+
+    - name: 🔎 Quality Gate - Test coverage shall be above threshold
+      env:
+          TESTCOVERAGE_THRESHOLD: 1
+      run: |
+            echo "Quality Gate: checking test coverage is above threshold ..."
+            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+            fi
+
+    - name: 👨‍🎤 Run Revive Action
       uses: docker://morphy/revive-action:v2
       with:
         config: revive.toml
+      continue-on-error: true
 
-    - name: Check formatting
+    - name: 👨‍🎤 Check formatting
       run: gofmt -l .
